Allow concurrent indexing in glean index cpp-cmake
facebookincubator/Glean pull request #271
Opened 2022-09-11 21:37 UTC by rleshchinskiy

This adds support for concurrent indexing based on the existing worklist framework. There are some shenanigans
related to progress reporting which mostly exist to make indexing LLVM nicer (script coming up).

The other major addition is the index-llvm.sh script which automates indexing LLVM source distributions using the parallel indexer - try the example suggested in index-llvm.sh --help. I'm not sure where the script should live. On my server indexing takes about 10 min with -j16.

Note that this includes #269 - we don't have stacked PRs so that one should probably be landed first.

2022-09-12 10:05 UTC, alpmestan approved these changes
LGTM (just spotted a typo)

2022-09-12 10:05 UTC, alpmestan commented on index-llvm.sh
> +    fatal "Couldn't local Glean source directory, please specify --glean"
s/local/locate/

2022-09-25 08:30 UTC, pepeiborra requested changes

2022-09-25 08:30 UTC, pepeiborra commented on glean.cabal.in
> +        Glean.Interprocess.Worklist
Missing files?

2022-09-25 08:33 UTC, pepeiborra approved these changes

2022-09-25 08:33 UTC, pepeiborra commented on glean.cabal.in
> +        Glean.Interprocess.Worklist
Nvm

2022-09-25 12:25 UTC, closed without merging